name: real_estate_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1
  # sdk: ">=3.4.4 <4.0.0"

dependencies:
  dio: ^5.6.0
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.4.1
  flutter_gen: ^5.7.0
  flutter_riverpod: ^2.5.1
  form_builder_file_picker: ^4.2.0
  form_builder_validators: ^11.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  logger: ^2.4.0
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
